inherit_gem:
  github-pages: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Exclude:
    - github-pages-health-check.gemspec
    - lib/github-pages-health-check/errors/*.rb
    
Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - lib/github-pages-health-check/domain.rb

Metrics/MethodLength:
  Exclude:
    - lib/github-pages-health-check/printer.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/github-pages-health-check/printer.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/github-pages-health-check/printer.rb

Metrics/AbcSize:
  Exclude:
    - lib/github-pages-health-check/printer.rb

Style/DoubleNegation:
  Enabled: false

Style/FileName:
  Enabled: false
