name: Publish Gem

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@086ffb1a2090c870a3f881cc91ea83aa4243d408 # v1.195.0
        with:
          ruby-version: '3.2'
      - name: Build gem
        run: |
          gem build github-pages-health-check.gemspec
      - name: Publish gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.PAGES_GEM_PUBLISHING }}
        run: |
          gem push github-pages-health-check-*.gem
