on: push
name: "GitHub Pages Health Check Tests"
permissions:
  contents: read
jobs:
  # Run sequential jobs because /script/test-redirections needs specific ports opened on the runner
  # and we cannot do that in parallel.
  ruby_3_0:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: script/cibuild-docker
      env:
        RUBY_VERSION: 3.0
  ruby_3_1:
    runs-on: ubuntu-latest
    needs: ruby_3_0
    steps:
    - uses: actions/checkout@master
    - run: script/cibuild-docker
      env:
        RUBY_VERSION: 3.1
  ruby_3_2:
    runs-on: ubuntu-latest
    needs: ruby_3_1
    steps:
    - uses: actions/checkout@master
    - run: script/cibuild-docker
      env:
        RUBY_VERSION: 3.2